#!/usr/bin/env bash
#
# bashpass/setup - prep bashpass

declare SDN SBN PGPF DB
SDN="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
SBN="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

if [[ ! -t 1 ]]; then
    echo -en "Fatal: You'll need to run ${SBN} in a terminal (or tty)!\n" >&2
    exit 1
elif [[ "${BASH_VERSINFO[0]}" -lt "4" ]]; then
    echo -en "Fatal: You'll need bash major version no less than 4.\n" >&2
    exit 1
elif [[ ! $(type -P sqlite3) ]]; then
    echo -en "Fatal: You need SQLite3 installed.\n" >&2
    exit 1
elif [[ ! $(type -P gpg) ]]; then
    echo -en "Fatal: You need GNU Privacy Guard v2 (gnupg) installed.\n"  >&2
    exit 1
fi

if [[ -z "${1}" ]]; then
    PGPF="sample.pgp"
    DB="${PGPF%%.pgp}"
elif [[ "${1}" =~ .pgp$ ]]; then
    PGPF="${1}"
    DB="${PGPF%%.pgp}"
else
    PGPF="${1}.pgp"
    DB="${PGPF%%.pgp}"
fi

FPPGPF="${SDN}/databases/${PGPF}"
FPDB="${SDN}/databases/${DB}"

echo -ne " This script will:\n \
 1. Make a ${DB} SQLite3 file ... \n \
 2. encrypt it to ${PGPF} \n \
 3. Execute bashpass ${PGPF} \n"

if [[ "$(read -rp " Continue? [Y/n]: " r;echo "${r:-y}")" =~ ^[Yy] ]]; then
    sqlite3 "${FPDB}" < "${SDN}/examples/ac.sql" && \
	gpg --default-recipient-self --output "${FPPGPF}" --encrypt "${FPDB}" && \
	"${SDN}/bashpass" "${PGPF}" && \
	echo -ne "From now on you'll be able to call bashpass with: bashpass ${PGPF}\n" >&2
fi
