1,https://liveleak.com/,traffic@accidents.io,crashpornaddict,S^G~cgKwQVq)0XJf,roadrageisgoodforu
2,https://wikipedia.org/,atruescolar@wikia.org,harrypotter,%KUpr@ROJwQ*Bd_+,voldemortdidnothingwrong
3,https://www.twitch.com/,streamer@twitching.com,sofaking,!HuiV7DW9d+*.7Kx,leroyjeeenkings
4,https://www.reddit.com/,reading@reader.com,geekerman,jd[d<q+;gLeCOyxj,r/RoastMe
5,https://twitter.com/,twitbot@botroost.net,chirpinator,somerandompass,SirChirpALot
6,https://facebook.com/,adummy@email.com,emanresu,o6vA/*2HSt4a_h!],foobuzzbar
7,https://www.google.com/,mail@gmail.com,googleuser,LL2Pto!vR&d!Y&I@,fizzbuzzbar
8,https://instagram.com/,selfindulgence@isgreat.me,notjustabimbo,fINjf>%lxVI{1ict,memyselfni
9,https://pinterest.com/,looking@pictures.jif,artzor,OBXpzhQvaC({UFGz,daliforprez
10,https://9gag.com/,me@toilet.pup,wcking,xCLRh~@dFw3jKn}1,yourawizardharry
